version: 2

updates:
  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'x:size/small'
  - package-ecosystem: 'cargo'
    directory: '/local-registry'
    schedule:
      interval: 'monthly'
    groups:
      all:
        patterns:
         - "*"
    labels:
      - 'x:rep/tiny'
